#! /usr/bin/env python

# This script is meant to update the tags on songs which are to be sync'd
# to my iPhone in order to allow for sane sorting.
#
# The iOS Music app, being horrible and whatnot, no longer allows the user
# to decide how albums are sorted. By default they appear to sort in
# reverse chronological order, which is backwards.
#
# If the date tags of two albums are equal, the Music app sorts by the
# album tag. This script works by setting all date tags to 9999 and
# prepending the date of each song to its album name.
#
# It's real sketchy, but it seems to work.

import os, sys

# from mutagen.easyid3 import EasyID3 as mutagen_id3
from mutagen.id3 import ID3 as mutagen_id3
from mutagen.id3 import TYER, TDRC, TDAT, TALB, TSOA

audio_endings = ('.mp3', '.m4a')

def main(path):
    for root, _, files in os.walk(path):
        for name in files:
            if name.endswith(audio_endings):
                filename = os.path.join(root, name)

                tags = mutagen_id3(filename)

                album_tag = 'TALB'
                date_tag = None
                if   'TDRC' in tags.keys() and str(tags['TDRC'].text[0]) < '3000':
                    date_tag = 'TDRC'
                elif 'TYER' in tags.keys() and str(tags['TYER'].text[0]) < '3000':
                    date_tag = 'TYER'
                elif 'TDAT' in tags.keys() and str(tags['TDAT'].text[0]) < '3000':
                    date_tag = 'TDAT'

                if date_tag and album_tag in tags.keys():
                    sort_album = str(tags[date_tag].text[0]) + u' - ' + tags[album_tag].text[0]
                    tags.setall('TSOA', [TSOA(text=sort_album)])
                    tags.setall('TALB', [TALB(text=sort_album)])

                    tags.delall(date_tag)
                    tags.setall('TDRC', [TDRC(text=u'9999')])

                    tags.save()


if __name__ == "__main__":
    main(sys.argv[1])
