#! /usr/bin/env python

# This script is meant to update the tags on songs which are to be sync'd
# to my iPhone in order to allow for sane sorting.
#
# The iOS Music app, being horrible and whatnot, no longer allows the user
# to decide how albums are sorted. By default they appear to sort in
# reverse chronological order, which is backwards.
#
# So far, this has not been successful...

import os, sys

from mutagen.easyid3 import EasyID3 as mutagen_id3
from string import lowercase as letters

audio_endings = ('.mp3', '.m4a')

def main(path):
    for root, _, files in os.walk(path):
        for name in files:
            if name.endswith(audio_endings):
                filename = os.path.join(root, name)

                tags = mutagen_id3(filename)

                sort_album = u''
                if 'date' in tags.keys():
                    sort_album += tags['date'][0] + ' - '
                if 'album' in tags.keys():
                    sort_album += tags['album'][0]
                else:
                    continue

                tags['albumsort'] = [sort_album]
                tags.save()

                # if 'date' in tags.keys():
                #     date = tags['date'][0]
                #     date_reversed = 2100 - int(float(date))

                #     date_mangled = number_to_digits(date_reversed)
                #     date_mangled += " " + date

                #     tags['date'] = [date_mangled]
                #     tags.save()

def number_to_digits(number):
    assert(number > 0)

    base = len(letters)
    digits = []

    while number:
        digits.append(letters[number % base])
        number /= base

    return ''.join(reversed(digits))

if __name__ == "__main__":
    main(sys.argv[1])
