#! /bin/bash

# This script is called by Transmission upon the completion of any download.
# It attempts to add import the downloaded files to my music library using
# beets, failing silently if the triggering download comprises non-music files.

BEET="/usr/local/bin/beet"

MUSIC_DIR="/Volumes/Data HDD/Music"
LOCAL_CONFIG="$MUSIC_DIR/beetsconfig-local.yaml"

IMPORT="import"
CONFIG="--config"
OPTIONS="--copy --nowrite --noautotag --resume"

$BEET $CONFIG="$LOCAL_CONFIG" $IMPORT $OPTIONS "$TR_TORRENT_DIR/$TR_TORRENT_NAME"
