#! /bin/bash

# This script is called by Transmission upon the completion of any download.
# It attempts to import the downloaded files to my music library using beets
# failing silently if the triggering download comprises non-music files.

set -o nounset

BEET="/usr/local/bin/beet"

MUSIC_DIR="/Volumes/Data HDD/Music"
LOCAL_CONFIG="$MUSIC_DIR/beetsconfig-local.yaml"

OPTIONS="--copy --nowrite --noautotag --resume"

LOG_FILE="/Users/julian/log/import-transmission-download-to-beets.log"

$BEET --config="$LOCAL_CONFIG" --verbose import $OPTIONS "$TR_TORRENT_DIR/$TR_TORRENT_NAME" 2>>"$LOG_FILE"
