#! /bin/bash

BEET="/usr/local/bin/beet"

MUSIC_DIR="/Volumes/Data HDD/Music"
LOCAL_CONFIG="$MUSIC_DIR/beetsconfig-local.yaml"

IMPORT="import"
CONFIG="--config"
OPTIONS="--copy --nowrite --noautotag --resume"

$BEET $CONFIG="$LOCAL_CONFIG" $IMPORT $OPTIONS "$TR_TORRENT_DIR/$TR_TORRENT_NAME"
